name: Linux

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'tools/**'
      - '.github/workflows/linux.yml'
      - 'raylib'
      - 'Makefile'

permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.6.0
      with:
        submodules: true

    - name: Setup Environment
      run: | 
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev gcc

    - name: Setup raylib
      run: |
        cd raylib
        mkdir build
        cd build
        cmake ..
        make -j4
        sudo make install
        cd ../..
        
    - name: Build rlplot debug
      run: |
        make bin/rlplot_dbg

    - name: Build and run unit tests
      run: |
        make test
        
    - name: Build rlplot release
      run: |
        make

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2.1.1
      with:
        version: 0.11.0
        cache: true

    - name: Build rlplot windows
      run: |
        make windows

    - name: Setup Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        source ./emsdk_env.sh
        cd ..

    - name: Build rlplot wasm
      run: |
        make EMSCRIPTEN=/home/runner/work/rlplot/rlplot/emsdk/upstream/emscripten www/index.wasm

    - name: Test artefacts
      run: |
        test -f www/index.wasm && ls -alFh www
        ls -alFh zig-out/bin/rlplot.exe
        ls -alFh bin/rlplot && strip bin/rlplot && ls -alFh bin/rlplot
        ls -alFh bin/rlplot_dbg

    - name: Fuzz test
      run: |
        make bin/rlplot_hl
        cat /dev/random | time bin/rlplot_hl
